export const EMAIL_TYPE_PREDICT_REQUEST  = "web/public/EMAIL_TYPE_PREDICT_REQUEST"
export const EMAIL_TYPE_PREDICT_SUCCESS  = "web/public/EMAIL_TYPE_PREDICT_SUCCESS"
export const EMAIL_TYPE_PREDICT_FAILURE  = "web/public/EMAIL_TYPE_PREDICT_FAILURE"